services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SymPress\Demo\Profiler\DemoProfilerCollector:
        tags:
            - { name: profiler.collector, priority: 45 }
