monolog:
    channels:
        - sympress_demo
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        demo:
            type: stream
            path: '%kernel.logs_dir%/sympress-demo.log'
            level: debug
            channels: [sympress_demo]
