imports:
    - { resource: '../vendor/sympress/orm/Resources/config/services.yaml' }

parameters:
    kernel.bundles_metadata: []
    orm.entity_classes:
        sympress-demo-plugin:
            - SymPress\Demo\Entity\DemoEventRecord

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
