parameters:
    profiler.storage_dir: '%kernel.project_dir%/var/cache/%kernel.environment%/profiler'
    profiler.collect: true
    profiler.collect_parameter: ''
    profiler.toolbar.ajax_replace: false
