name: JavaScript

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typecheck:
    name: TypeScript
    uses: sympress/workflows/.github/workflows/javascript-static-analysis.yml@cd809f3986df3ea617d2d26bdf21ab69cae19c1e
    with:
      node_version: '24'
      working_directory: packages/sympress-demo
      script: typecheck

  npm-audit:
    name: npm audit
    uses: sympress/workflows/.github/workflows/javascript-static-analysis.yml@cd809f3986df3ea617d2d26bdf21ab69cae19c1e
    with:
      node_version: '24'
      working_directory: packages/sympress-demo
      script: audit

  production-build:
    name: Production build
    uses: sympress/workflows/.github/workflows/javascript-static-analysis.yml@cd809f3986df3ea617d2d26bdf21ab69cae19c1e
    with:
      node_version: '24'
      working_directory: packages/sympress-demo
      script: build:production
